import { Unbounded } from "next/font/google";
import "./globals.css";
export const dynamic = "force-static";
const unbounded = Unbounded({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${unbounded.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
